### ISSUE TITLE
Geothermal plant pipe infrafrustructure not shown

### ISSUE THREAD

**Issue by robert-ancell** [openinframap/openinframap#100]
In geothermal schemes there are often a large number of water/steam pipes in use tagged as man_made=pipeline, substance=hot_water. These are not rendered in Open Infrastructure Map (substance=water is).

e.g. Geothermal plants:
https://www.openstreetmap.org/#map=15/-38.6221/176.0770
![osm-geothermal-pipes1](https://user-images.githubusercontent.com/126560/114101384-c8618b00-9919-11eb-8a1d-de7707846cff.png)

https://openinframap.org/#13.97/-38.62087/176.07134
![osm-geothermal-pipes2](https://user-images.githubusercontent.com/126560/114101396-cbf51200-9919-11eb-8965-2424b0bc098a.png)

**Comment by ddolobb** [comment]
Bump on a similar issue. A great addition would be the visibility of hot water pipelines, already present as a tag in OSM. When 'water' is selected it only seems to visualise lines tagged under man_made=pipeline and substance=water. Pipelines tagged under substance=hot_water would be a welcome addition. 

Specifically I have been making edits and additions to Iceland's geothermal district heating network, which some hot water piplines traverse tens of kilomitres from extraction sites to cities/towns, would be wonderful to see them in OpenInfraMap (maybe with a red colour :) ). 

I believe Iceland has some of the world's longest district heat distribution pipelines, the longest at 63km long, transporting 85°C water to the town of Akranes. Among other long distance geothermal hot water transmissions are 2x 25km (1m diameter) to Reykjavik from Hellisheiði/Nesjavellir CHP plants as well as a new 20km pipeline to Höfn - would be great to visualise in OIM. 

As well as steam piplines in the vicinity of geothermal plants, some district steam heating systems exist which would be an interesting addition to OpenInfraMap, such as ConEd's famous NYC district steam system.

**Comment by russss** [comment]
Added, along with steam, sewage, and a few others.

**Comment by ddolobb** [comment]
big thanks to russss to address this issue quickly, with differentiated colours for hot water, steam and sewage. Looking good!

**Comment by robert-ancell** [comment]
Thanks @russss! I noticed that a number of these pipelines have since been changed to [substance=geothermal_fluid](https://wiki.openstreetmap.org/wiki/Tag:substance%3Dgeothermal_fluid) which is not an official tag, but more accurate than hot_water. Ideally this would be made an official tag but I'm not aware of any process for that. Would you consider adding this to the list of new tags?

**Comment by flacombe** [comment]
Hi @robert-ancell 
This value could be discussed on [substance=*](https://wiki.openstreetmap.org/wiki/Key:substance) page or part of a bigger proposal with complete [proposal process](https://wiki.openstreetmap.org/wiki/Proposal_process)

We are currently lacking of documentation in several substances values, missing pages sometimes. I think utility=* is now ok and we need to spend some time on substance=* values for now.

**Comment by russss** [comment]
I decided not to import `substance=geothermal_fluid` because it had a comparatively small number of uses worldwide and it was undocumented. I'm personally not a fan of the proposal process but I try not to adopt low-usage tags unless they're adequately documented with a justification for why they're necessary.

We probably could do with a proposal process to unify `wastewater` vs `sewage` vs `waterwaste` vs `rainwater`, and also maybe `hot_water` vs `steam`. It also appears there's some use of the `usage=heat` tag along with `substance=water`, which is probably overloading the `usage` key too much.

**Comment by russss** [comment]
...also in many cases `substance=hot_water` is not going to be pure water - it's going to be district heating water with additives, or process water, or whatever. So I think it's unclear why `geothermal_fluid` deserves that distinction when district heating water doesn't, for example.

I'd personally lean towards `hot_water` as a top-level tag, and some kind of sub-tag indicating its purpose.

**Comment by flacombe** [comment]
To me ```hot_water``` and ```steam``` are valid substances.

```usage=heat``` may be replaced by ```utility=heating``` instead.
