### ISSUE TITLE
Improve pipeline colors

### ISSUE THREAD

**Issue by timoo54** [openinframap/openinframap#106]
Currently the colors of pipelines are very pale especially at high zoom levels.
The color of oil pipelines is also very similar to the color of country borders, e.g:
https://openinframap.org/#6.83/45.927/16.992

I'd like to suggest to either
- increase the width of the pipelines or
- use more color saturation
- use different colors

I'd suggest to use a "dark" yellow or orange (e.g. ffbf00) for gas and a brown-red color (e.g. 993300) for oil, similar to the often used marker colors.
Here a link for comparison with the current colors:
https://www.colorcombos.com/combotester.html?color0=e0dc7e&color1=ffbf00&color2=e5b393&color3=993300&show_text=

EDIT: Another problem is that there is no destinction between small local pipelines and big major pipelines like there is for power lines.
E.g. the tag usage=transmission could be used to highlight those pipelines with the new colors and keep the old colors (but still with some more saturation) for pipelines without this tag?

PS: Also a split of oil and gas might be useful in the future as there are areas where pipelines are overlapping and hiding each other. Or just to be able to filter the view accordingly.

**Comment by russss** [comment]
I'm now rendering usage=transmission pipelines more prominently (see #154).
