### ISSUE TITLE
How to add a sewage layer.

### ISSUE THREAD

**Issue by pyrat** [openinframap/openinframap#116]
Hey, 

I am not sure if you deem it out of the scope of this project but would it be possible / what would be involved in adding sewage underground pipelines to openinframap. 

I was hoping to use openinframap as a tool to map local infrastructure in my village.

**Comment by xephos1one** [comment]
Is there any news on this issue?
Sewerage, manhole covers and water treatment plants are an important part of infrastructure that would be great to see at OIM.

**Comment by russss** [comment]
I've added sewage pipelines to the water layer now (see #100).

Water and sewage treatment plants will be added in the next re-import.
