### ISSUE TITLE
No site icon - Add favicon

### ISSUE THREAD

**Issue by jidanni** [openinframap/openinframap#125]
![20211125T232147](https://user-images.githubusercontent.com/1230959/143467254-f0599109-f1ea-43f2-87fc-b2baf28b90b4.jpg)
https://en.wikipedia.org/wiki/Favicon

**Comment by russss** [comment]
You already reported this in #113.

**Comment by jidanni** [comment]
https://github.com/openinframap/openinframap/issues?q=is%3Aissue+icon+is%3Aopen missed it.

**Comment by jidanni** [comment]
OK, no patterns / regexps possible.
https://docs.github.com/en/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax
