### ISSUE TITLE
Add EIA 860 plant codes to stats pages

### ISSUE THREAD

**Issue by JesseWeinstein** [openinframap/openinframap#129]
It'd be nice to show the `ref:US:EIA` key on power plant stat pages, where present (only in the USA). And it could even be linked to https://data.catalyst.coop/pudl/plants_entity_eia (especially when the licensing for that is clarified).

**Comment by flacombe** [comment]
It's related (not a duplicate) to #65

**Comment by russss** [comment]
I've added this, and there's now a link from the info popup on the map to the stats page for a plant.
