### ISSUE TITLE
start_date

### ISSUE THREAD

**Issue by ZEE6de** [openinframap/openinframap#130]
the start_date tag should be shown too when clicking on objects. This shouldn't be too hard to implement.

**Comment by russss** [comment]
I've added start_date to a load of objects now.

**Comment by flacombe** [comment]
I think we still miss it on several features:
* power=pole, towers => https://www.openstreetmap.org/node/4917709313
* power=cable, line => https://www.openstreetmap.org/way/730907158

As part of global osm lifecycle features, shouldn't it be implemented on any feature instead?

**Comment by russss** [comment]
Oops, I missed those. They should be added now (subject to caching)
