### ISSUE TITLE
Hot water solar panels are rendered in power category

### ISSUE THREAD

**Issue by guerda** [openinframap/openinframap#131]
I'm not 100% if this is a bug in OpenInfraMap or it's a mapping error, so bear with me.

I discovered that solar panels which are not PV, but for thermal use are rendered in the "Power" category.
Here's one entity which is for hot water production, but not for electricity. It still gets rendered under "Power", which is misleading.

```
area=yes
generator:method=thermal
generator:output:heat=no
generator:output:hot_water=yes
generator:place=roof
generator:source=solar
generator:type=solar_thermal_collector
location=roof
power=generator
```
In the Wiki, it says that power=generator is also applicable for hot water generation. https://wiki.openstreetmap.org/wiki/Tag:power%3Dgenerator

### Screenshot
![image](https://user-images.githubusercontent.com/230782/149124192-36609a4c-eb5f-4a9d-b787-0b79a26abd6f.png)
![image](https://user-images.githubusercontent.com/230782/149124209-96870127-d2ec-43f8-bd00-f83652696af0.png)

### Link to where this issue occurs on OpenInfraMap
https://openinframap.org/#17.9/51.241598/6.708645/P
### Link to the corresponding entity on OpenStreetMap
https://www.openstreetmap.org/way/1010180838

**Comment by guerda** [comment]
Looks like there's already a Todo in the code: https://github.com/openinframap/openinframap/blob/main/mapping/power.py

 
```
 ​        ​str_col​(​"generator:output"​, ​"output"​), ​# TODO: should be generator:output:electricity
```

**Comment by guerda** [comment]
I assume that a filter for [`generator:method=photovoltaic`](https://wiki.openstreetmap.org/wiki/Tag:generator:method%3Dphotovoltaic) must be added to `tegola/layers.yml`.
This looks like the right place: https://github.com/openinframap/openinframap/blob/main/tegola/layers.yml#L244

Unfortunately, I do not have any more insights on this.

**Comment by guerda** [comment]
Maybe it's https://github.com/openinframap/openinframap/blob/main/mapping/power.py#L136 this line where the condition is missing.

**Comment by russss** [comment]
I've excluded generators tagged as `generator:type=solar_thermal_collector`, as I reckon it's more likely that generators missing a type tag are photovoltaic. (Generators with `generator:method=thermal` can generate electricity.)

**Comment by guerda** [comment]
Thank you!

**Comment by sb12** [comment]
> I reckon it's more likely that generators missing a type tag are photovoltaic

Looks like this change also affects solar generators without type, e.g. in this solar plant:
https://openinframap.org/#15.49/49.262365/8.527155/L,P,S
https://www.openstreetmap.org/way/193451204
![grafik](https://user-images.githubusercontent.com/5783139/153725537-4fc95df6-6b06-42d3-871a-ec4082518611.png)
![grafik](https://user-images.githubusercontent.com/5783139/153725628-c0e27d48-fcab-4fd0-b657-693d7a1c16cc.png)

**Comment by russss** [comment]
Thanks - there was an issue with nulls there. I believe it's fixed now but it might take a day for the caches to expire.
