### ISSUE TITLE
Missing a lot of solar power generation

### ISSUE THREAD

**Issue by JaapKeuter** [openinframap/openinframap#132]
https://github.com/openinframap/openinframap/blob/dd5fb9fbe2332a507b3ffb9ab93fa2e566bc68be/tegola/layers.yml#L236

This part of the code to generate the solar power generation heat map is only using the data of solar installations with defined individual generators. Solar installations tagged as `plant:source=solar` (as per [the wiki](https://wiki.openstreetmap.org/wiki/Tag%3Apower%3Dplant)) are not included.

An example can be seen [here](https://www.openstreetmap.org/way/795642158) vs [here](https://www.openstreetmap.org/way/972778576). The former shows up on the heat map, the latter doesn't.

**Comment by russss** [comment]
This is (somewhat) intentional. If we included plants as well, we'd double-count those plants which also have generators mapped. I do plan to include them but I'll need to investigate the performance of checking if generators are contained within a plant.

**Comment by russss** [comment]
Solar plants are now included in the heatmap layer (subject to caching)

**Comment by JaapKeuter** [comment]
> Solar plants are now included in the heatmap layer (subject to caching)

Indeed they are now. Thank you for the addition.
