### ISSUE TITLE
Exclude from stats search the power plants in exclaves

### ISSUE THREAD

**Issue by muralito** [openinframap/openinframap#133]
The search for stats in Uruguay includes a power plant https://openinframap.org/stats/area/Uruguay/plants/907385266 located in Martin Garcia Island, and under Argentina jurisdiction.

**Comment by russss** [comment]
Good spot. The countries dataset comes from [marineregions.org](https://www.marineregions.org/) who, in turn, get their land borders from ESRI. I've let MarineRegions know about the error.

**Comment by russss** [comment]
Just for the record, this error is now listed in the [known issues](https://www.marineregions.org/files/EEZ_land_union_v3_known_issues.txt) for this dataset. They don't update it very often so it may well be a while before it's fixed.
