### ISSUE TITLE
Compensator icons

### ISSUE THREAD

**Issue by Gazer75** [openinframap/openinframap#136]
Could we have a separate symbol for shunt reactors vs capacitors?
For reactors the symbol shown in this page could be used:
https://www.semanticscholar.org/paper/Neutral-earthing-reactor-protection-Dobrzy%C5%84ski-Lubo%C5%9Bny/00ca8cbd3ca377aef053a8a22ce96fecb970b5b4/figure/0

The NER at the bottom in the picture is probably what some call a "petersen coil", but not sure.
The symbol in the dashed box of that one could be a good icon for shunt reactors.

For STATCOM and SVC a black ring with STC and SVC inside could be used.

If anyone have any better suggestions please post them.

**Comment by russss** [comment]
I've added these now, there are new icons for shunt/series reactors/capacitors and filters, and the rest are use an abbreviation-in-a-box.
