### ISSUE TITLE
Planetiler

### ISSUE THREAD

**Issue by wipfli** [openinframap/openinframap#137]
OpenInfraMap is such a cool project. I am amazed by all the information that is available on this map and have used it as an inspiration in the past to make a map for hot-air ballooning (where power lines are quite important...).

I just wanted highlight that you might be interested in planetiler. It is like OpenMapTiles but 160x faster, i.e., it generates a `planet.mbtiles` file from a `planet.osm.pbf` file in something like 1 hour on a single machine (with 128 GB ram, 32 cores, and 600 GB SSD). I guess you could extend the existing profiles to cherry-pick the OSM data you need.

https://github.com/onthegomap/planetiler

**Comment by russss** [comment]
Thanks - I don't actually use OpenMapTiles/MapTiler for the overlay data. It's updated incrementally in realtime with imposm3 and tegola, which is faster than re-generating the whole planet at once.

At some point I would like to sort out my own background map, but I need more disk space first. I'll definitely take a look at planetiler when I get round to that.
