### ISSUE TITLE
No rendering man_made=street_cabinet street_cabinet=power

### ISSUE THREAD

**Issue by CharlesMaZ** [openinframap/openinframap#139]
If you're reporting an issue with rendering, please provide:

**Comment by CharlesMaZ** [comment]
and name/ref power=transformer

**Comment by Matthias84** [comment]
I also suggest a [streetcomplete quest](https://github.com/streetcomplete/StreetComplete/issues/4505) to help to distinguish this tags and giving OIM more objects to show up

**Comment by flacombe** [comment]
It should be said a proposal is currently under RFC and adjustments still required on solutions to be adopted, to deprecate street_cabinet=* as utility mark.
https://wiki.openstreetmap.org/wiki/Proposed_features/Utility_facilities

Any power/telecom/water/whatever should go under common utility=* key please.

**Comment by russss** [comment]
Closing in favour of #157.
