### ISSUE TITLE
Openinframap.org is unavailable. Cloudflare's Error 1020 Access denied 

### ISSUE THREAD

**Issue by un-logic** [openinframap/openinframap#140]
Hi! I've noticed yesterday, that [Openinframap.org](https://openinframap.org) service is [unavailable](https://downforeveryoneorjustme.com/openinframap.org).
Instead Cloudflare says:

> Error 1020 Ray ID: wh4t3v3r• 2022-03-02 05:01:09 UTC
> Access denied
> Ray ID: wh4t3v3r• Your IP: 85.112.43.210 • Performance & security by Cloudflare

I couldn't find any info on planned downtime or restrictions from @russss.
Any comments are welcome.

**Comment by flacombe** [comment]
It sounds like a Cloudflare problem, or temporary server downtime.

Access on OIM works well from France currently.

**Comment by un-logic** [comment]
Yes, it is now online. Never seen this kind of error from Cloudflare, usually it's some other. Glad to see OIM back up!

**Comment by un-logic** [comment]
Little bit of follow up.
So, recently I've been running into more "hiccups" when accessing [Openinframap.org](https://openinframap.org/) from Russia. It seemed like access to the site was sometimes blocked due to [Roskomnadzor's](https://eng.rkn.gov.ru/about/) mandate, but checking it's [Unified register](https://eais.rkn.gov.ru/en/#form) revealed that 

> The requested address is not blacklisted

Turned out that Cloudflare's name servers sometimes resolve IP addresses that were in fact blacklisted as a result of numerous court rulings all over Russia. IP addresses for these legal cases usually obtained by performing simple command
`ping http://misbehaving.site`
often this results in groups of Cloudflare's IP addresses to be put on block list. 

In the end, if you are in Russia there are two ways: 

1. Keep on refreshing page for a few minutes, it will load eventually
2. Use one of available block evading techniques

Anyways, I'm glad, that OIM exists and still functions.
