### ISSUE TITLE
Power=pole + transformer=distribution + location:transition=yes rendering problem

### ISSUE THREAD

**Issue by Gazer75** [openinframap/openinframap#141]
If the pole has a transformer and a transition the transformer icon is not rendered, and the triangle is shifted to where the transformer icon would normally be beside the black dot.

https://openinframap.org/#17.9/60.394498/11.605683
https://openinframap.org/#17.9/60.399439/11.60515
https://openinframap.org/#17.9/60.405692/11.60254

**Comment by russss** [comment]
This has been fixed
