### ISSUE TITLE
Pipeline overground

### ISSUE THREAD

**Issue by livioavalle** [openinframap/openinframap#143]
Would be nice if also the overground pipeline were rendered, so there will be continuity with some pipeline system that are mixed, undergroun and overground, like shown in the screenshot.

### Screenshot
![immagine](https://user-images.githubusercontent.com/12595115/158490283-fce3d2eb-b3d3-4570-bfa3-17b55d480550.png)
![immagine](https://user-images.githubusercontent.com/12595115/158490336-d376da50-4a95-4772-bed2-a8e08ab66daa.png)
### Link to where this issue occurs on OpenInfraMap
https://openinframap.org/#15.34/70.091189/-148.582507/L,O
### Link to the corresponding entity on OpenStreetMap
https://www.openstreetmap.org/way/8987867

**Comment by flacombe** [comment]
Overground pipelines are rendered.

Problem here is `substance` tag.
Underground part got substance=oil and the overground part got nothing.
Add substance=oil and it will be shown on OIM.

Cheers

**Comment by russss** [comment]
Yup - I think @flacombe has got it correct here. Underground pipelines are definitely rendered.
