### ISSUE TITLE
Missing `stats.power_line` and `countries.country_eez` tables

### ISSUE THREAD

**Issue by amihalik** [openinframap/openinframap#146]
I'm setting up a local instance of openinframap.  I have the postgis, imposm, and tegola components working, and now I'm trying the web-backend.

When I open `http://localhost/stats/area/United%20States`, I get the following error in the server logs:

`asyncpg.exceptions.UndefinedTableError: relation "countries.country_eez" does not exist`

When I open `http://localhost/stats`, I get the following error in the server logs: 

`asyncpg.exceptions.UndefinedTableError: relation "stats.power_line" does not exist`

I found the code that refers to these relations, but I cannot find the .sql to actually create them.  Could you provide some links, advice, or references?

Thanks!

**Comment by russss** [comment]
Sorry for the very slow response here! I've now documented the country tables [here](https://github.com/openinframap/openinframap/blob/main/imposm/README.md) and the stats tables are in [schema/stats.sql](https://github.com/openinframap/openinframap/blob/main/schema/stats.sql)
