### ISSUE TITLE
Water_works and some other elements are not rendered as part of the water infrastructure layer

### ISSUE THREAD

**Issue by kalon33** [openinframap/openinframap#147]
OSM tag identifying water works (https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_works) are not rendered as part of the water map layer.

Not sure these ones are too : 

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwastewater_plant

https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_tower

man_made=pumping_station in combination with pumping_station=water is also not rendered (https://www.openstreetmap.org/way/146303992), whereas it is part of the water distribution infrastructure.

More generally, elements with the utility=water tag should be rendered according to OSM documentation (https://wiki.openstreetmap.org/wiki/Tag:utility=water) as they are "part of the infrastructure related to water treatment, transmission and distribution towards industries and domestic consumers" (so that would also include reservoirs notably).

### Link to where this issue occurs on OpenInfraMap (example for water_works)
https://openinframap.org/#15.29/48.74928/2.425345/W

### Link to the corresponding entity on OpenStreetMap (example for water_works)
https://www.openstreetmap.org/way/639202457

Could you please make them rendered ? Thanks a lot for your help. Don't hesitate to ask if you need more information.

**Comment by wolfy1339** [comment]
There's an issue open already with some of the tags yore suggesting to render.
https://github.com/openinframap/openinframap/issues/98

**Comment by russss** [comment]
These are now added (see #98)
