### ISSUE TITLE
Prioritizing oil and gas pipelines by the usage=* tag, diameter and/or pressure

### ISSUE THREAD

**Issue by Janjko** [openinframap/openinframap#151]
The oil/gas layer is getting a bit crowded in places where there are a lot of pipelines mapped. Maybe filter them out by showing only [usage=transmission](https://wiki.openstreetmap.org/wiki/Tag%3Ausage%3Dtransmission) pipelines on earlier zooms. If that isn't enough, maybe experiment with different diameters and pressures. Those tags still aren't that prevalent, but this might push it.

**Comment by Hiausirg** [comment]
Diameter & pressure are only mappable with access to internal documentation / or on larger, widely known usage=transmission pipelines. (Usually, of course)
I think it's more important now to make sure that diameter/pressure/usage tags are actually displayed at all - which shouldn't be too much work.
But if one implements something like your suggestion, then also on/off switchable. And then also with such things like roughly mapped (very inconsistently/missing voltages) minor_lines, which affect the map image much more negatively. But that's another topic now.

With crowded, do you mean Southern Texas? ;)

**Comment by Janjko** [comment]
> With crowded, do you mean Southern Texas? ;)

I was thinking about France and Germany, but now that I see Texas, wow, this issue is really a priority :)

**Comment by flacombe** [comment]
> Diameter & pressure are only mappable with access to internal documentation

Sometimes it is written on the ground (and seen from aerial imagery)
https://twitter.com/InfosReseaux/status/1236962404937928704

Or written on markers to warn about underground pipeline and allowing to identify exactly which pipe it refers to when digging.

It sounds relevant to change display based on usage=* to begin with. Diameter can be a bit confusing, when you deal with 50mm wide transmission pipelines.

I had a look at southern Texas, what a tremendous contribution... and a tremendous network as well!

**Comment by russss** [comment]
I'm now prioritising stuff by `usage=transmission`. It's still not perfect but it's better.
