### ISSUE TITLE
Background imagery

### ISSUE THREAD

**Issue by Hiausirg** [openinframap/openinframap#152]
I think that adding background images to the map as a selectable option (instead of the standart map) can lead to very interesting results.
I used my insane editing skills to make an example:

![Unbenannt](https://user-images.githubusercontent.com/102484092/194279279-9d717203-137f-47e0-bff2-08cb87916294.PNG)

**Comment by russss** [comment]
Unfortunately all the good worldwide aerial imagery costs money, and we don't have any budget for this. (The imagery visible in OSM editors is specifically licensed for *editing* OSM and we can't use it in OpenInfraMap.)

If there is a way of showing decent-quality aerial imagery without payment then I'd be happy to reconsider, but as it stands I'm going to close this issue.
