### ISSUE TITLE
More pipeline types/colors

### ISSUE THREAD

**Issue by Hiausirg** [openinframap/openinframap#154]
There is a need for more 'pipeline rendering types'.
First, the category "oil pipeline" should be divided into (crude) oil and (petroleum) product pipelines. Oil pipeline (substance=oil) can be rendered as a black line, product (substance=fuel) as the current orange line.

New types:
- Hydrogen (substance=hydrogen). Render as a blue line - the gulf coast has many, but also one major system across belgium: https://overpass-turbo.eu/s/1nH0
- Carbon dioxide/monoxide. Render as brown? line - also quite a few at the gulf coast: https://overpass-turbo.eu/s/1nH2
 I also know a system from Colorado to east Texas (for use at 'enhanced oil recovery') (not yet mapped)
- Natural Gas Liquids (substance=ngl). Usually liquids seperated from gas well outputs (which are not oil). Maybe a bright yellow? Currently ~7700 km mapped.
- Y-Grade (substance=y-grade). Subtype of NGL, has to be fractionated. Around 1500 km mapped.
- Ethylene/Propylene (Also NGL subtype, very important chemical feedstocks (liquid)) Theroretically white/colorless would be best, but since this is not visible, maybe only a generic green (and also include various other chemicals (see taginfo)). Around 4800 km mapped.

These are only the most urgent types. But there are tons of other types - expecially various chemicals which are mapped. Take a look at the [Houston Ship Channel](https://openinframap.org/#10.61/29.7321/-95.1074/L,O,T,W) - the US center for oil/products and the petrochemical industry. (Two main petroleum product pipelines orginate here, Colonial supplying the East Coast and Explorer the Midwest) It looks already dense on the map, but the reality and the data in OSM is MUCH denser. 
(Off-topic: Note that the linked area is not relevant as a natural gas hub - all those gas transmission lines are all for local usage as fuel or feedstock. The major interstate pipelines run north of Houston)

And two other things: 
- "diameter=" and "start_date=" can be rendered along operator and other things - just as they are, no data conversation or anything needed.
- "industrial=(petro)chemical" can be rendered as a green area, just like "industrial=oil" is rendered as a orange area.

**Comment by russss** [comment]
Definitely agree with this!

I've been neglecting this layer a bit because it's hard to find a colour scheme which works alongside the power layer. I think I'll have to change the layer selection so that you can't see both power and oil/gas at once.

I think the OSM wiki needs a bit of an update to add these additional substances - the [substance page](https://wiki.openstreetmap.org/wiki/Key:substance) is missing a few of these, and ideally they could do with individual Tag: pages as well.

**Comment by russss** [comment]
Alright I think this is an improvement at least.

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/45057/233626323-2a3a5a91-a208-4724-8b0e-6061a2b1ffce.png">

I've added a whole load more substances and a few more colours. I'm sure there's more work to be done here, and adding other `industrial=` uses and so on will require a re-import.
