### ISSUE TITLE
Update icon loading pipeline

### ISSUE THREAD

**Issue by russss** [openinframap/openinframap#165]
SpriteZero is now desperately old and I suspect that there's no real advantage to using sprites any more, particularly with HTTP/2. I think the best approach here is:

* Render SVG to PNG in the build pipeline
* Ideally: for 1-bit images, convert them to a [SDF](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/) which is more efficient and allows icons to be recoloured.
* Write some javascript to load these in

(This also hopefully means we can dump Webpack in favour of Vite which will make me very happy.)

**Comment by mathiash98** [comment]
Completely agree with you here. Using Vite would be nice.

Do we even need to convert SVG to PNG? Keeping them as SVG would allow coloring if I'm not mistaken.

**Comment by russss** [comment]
MapLibre/Mapbox GL doesn't support SVG icons (for what I understand is a good reason - it's not practical to render them in WebGL).

SDF is meant to be the magic solution to this (resolution-independent, easy to render in shaders, re-colourable, tiny file size) as long as your icon is only 1-bit colour (which not all the OpenInfraMap icons are).

**Comment by mathiash98** [comment]
Created a suggestion for a migration to Vite in #166
