### ISSUE TITLE
Electrical output values on solor generators

### ISSUE THREAD

**Issue by tntchn** [openinframap/openinframap#168]
The electricity output data (plant:output:electricity) on a power plant feature can be rendered as XX MW or other units on the feature dialog, but the similar data generator:output:electricity not works as well as the plant.

The 'Electrical Output' value should be 29 MW instead of 29.(many zeroes)
![截圖 2023-09-12 下午4 41 00](https://github.com/openinframap/openinframap/assets/15895303/4d22731a-a2f1-436f-a6c3-11d6f5ba8022)
https://www.openstreetmap.org/relation/2523806
https://openinframap.org/#14.88/51.5269/11.51957

**Comment by russss** [comment]
Ugh, is this the return of #34... I'll take a look but it might not be immediately.

**Comment by jmarchon1** [comment]
I appear to be experiencing this too. Or is this in the screenshot something different?

![Screenshot_20231115-215320.png](https://github.com/openinframap/openinframap/assets/50030493/c4c91d54-e8a0-4867-a3b1-db5c14efed6b)

**Comment by starsep** [comment]
Another example of float issue: https://openinframap.org/#17/49.752025/19.537108
![image](https://github.com/openinframap/openinframap/assets/2798728/5db135b5-15d2-433b-8f7e-5e4c5900e4c5)

**Comment by russss** [comment]
I think these should all be fixed now.
