### ISSUE TITLE
Subtransaction issue during a parallel operation in pgsql

### ISSUE THREAD

**Issue by flacombe** [openinframap/openinframap#169]
Hello

I got the following error in pgsql log while browsing the map.
It seems some Pl/pgsql functions raise parallel issues I can't manage to understand.
The function convert_voltage is already PARALLEL UNSAFE so it shouldn't be involved in a parallel processing, should it?

> 2023-10-31 20:36:55.891 UTC [1739] ERROR:  cannot start subtransactions during a parallel operation
>2023-10-31 20:36:55.891 UTC [1739] CONTEXT:  PL/pgSQL function convert_voltage(text) line 7 during statement block entry
>	PL/pgSQL function line_voltages(text,integer) line 18 at assignment
>	SQL statement "SELECT osm_power_line.osm_id, osm_power_line.geometry, 
>				osm_power_line.type, osm_power_line.location, osm_power_line.line,
>				osm_power_line.voltage, osm_power_line.circuits, osm_power_line.frequency,
>				osm_power_line.construction, osm_power_line.tunnel,
>				line_voltages(osm_power_line.voltage, osm_power_line.circuits) AS voltages,
>				osm_power_line.tags
>				FROM osm_power_line
>				WHERE osm_power_line.geometry && search_geom"
>	PL/pgSQL function power_lines(integer,geometry) line 25 at RETURN QUERY

**Comment by russss** [comment]
Hmm.

Firstly, have you checked that the function as defined in your database is actually marked as `PARALLEL UNSAFE`? I'm not sure when I added that flag.

If that doesn't work, maybe try marking the `power_lines` function as `PARALLEL UNSAFE` as well and see if that helps. Which Postgres version are you running?

I should try and work out a way of making this `convert_voltage` function parallel-safe somehow.

**Comment by flacombe** [comment]
Well, i've droped `line_voltages` and redefined to be sure the parallel unsafe flag is on and it looks good. No more errors.
Simplest solutions are the best, thank you.

I'm running PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1) btw.
