### ISSUE TITLE
Get material and location transitions in any domain

### ISSUE THREAD

**Issue by flacombe** [openinframap/openinframap#17]
There are 2 keys it may be great to import regarding supports for power, telecom, pipeline, whatever
* material=*
* location:transition=*

Material is applicable on : power lines, power supports (all of them), telecom supports, pipelines
Transitions are applicable on power supports, telecom supports and pipelines, pretty often as nodes.
If a power line goes underground on a portal mapped as a way, the location:transition=yes will be on the connecting insulator. Example here : http://www.openstreetmap.org/node/4226815117

This is a reminder for further new data imports, triangle would be a good symbol for transitions on map.

**Comment by russss** [comment]
Material (and design) is now being shown in the infobox so I think this is done.
