### ISSUE TITLE
Voltages are not in descending order in the info popup

### ISSUE THREAD

**Issue by wolfy1339** [openinframap/openinframap#172]
There has been a recent change to how voltages are displayed in https://github.com/openinframap/openinframap/commit/6fc9a86d8ba48d885c61c04d1b448899254fccec, which really is nice, but it seems that now the voltage order is not the same as tagged in OSM, nor in descending order.

Take 2 different electrical substations with 3 different voltage levels, and the voltages are not displayed the same way.

Here's a 230-120-69 kV substation
![image](https://github.com/openinframap/openinframap/assets/4595477/aad17e3c-ed1a-48be-8d69-c4bb8fc4d219)

and here's a 735-315-230kV substation

![image](https://github.com/openinframap/openinframap/assets/4595477/e0b880a2-7318-4bcf-9079-6f26383af579)

Notice in the first one, the voltages aren't showing in a descending order, while the second one shows how you would expect.
The issue seems to happen when the converted voltage level in kV is only 2 digits (ex: 69kV) and there are 3 digit kV voltage levels (ex: 735kV)

### Link to where this issue occurs on OpenInfraMap
https://openinframap.org/#16.05/46.443707/-70.992157
https://openinframap.org/#15.08/46.70976/-71.19012
https://openinframap.org/#16.94/46.698516/-71.295646
### Link to the corresponding entity on OpenStreetMap
https://www.openstreetmap.org/way/143914257
https://www.openstreetmap.org/way/100582397
https://www.openstreetmap.org/way/96456442

**Comment by russss** [comment]
Yes, naturally Javascript's sort method converts things to strings by default... thanks!
