### ISSUE TITLE
A few minutes of browsing OIM puts tons of entries into browser history

### ISSUE THREAD

**Issue by jidanni** [openinframap/openinframap#174]
A few minutes of browsing OIM puts tons of entries into one's  [browser history](chrome://history/).
Yes, same problem on the main OSM.ORG site.

**Comment by russss** [comment]
This doesn't happen for me in Firefox or Chrome - which browser are you using?

As far as I know we are using the appropriate API to do this, so I would suggest this is a browser bug.

**Comment by jidanni** [comment]
All I know is each time I grab the screen and move it, another Chome history entry is generated. Check with CTRL+H in Chrome.

**Comment by russss** [comment]
Ah right, I see the issue, it doesn't affect the back button, only the history.

Google Maps does exactly the same so I don't think there's anything we can do here. The alternative would be that it doesn't update the URL bar at all, which I think would be worse.
