### ISSUE TITLE
man_made=utility_pole not rendering

### ISSUE THREAD

**Issue by RedAuburn** [openinframap/openinframap#178]
### Screenshot
![image](https://github.com/openinframap/openinframap/assets/26939824/d501efcb-e9ca-4731-992c-dbd91ced45fb)
the rendered dots are `power=pole`, but the `man_made=utility_pole`s further north aren't rendered

Link on OpenInfraMap: https://openinframap.org/#17.9/55.615478/-3.410916/L,O,P,S,T,W
Link on OpenStreetMap: https://www.openstreetmap.org/node/11100234391

**Comment by flacombe** [comment]
Hello

You should consider using utility=* to describe to which utility the pole is referring to (possibly power here).

It is similar to #176

**Comment by russss** [comment]
Closing this one in favour of #176.
