### ISSUE TITLE
Unable to see information about power plant from the map

### ISSUE THREAD

**Issue by Jean-BaptisteC** [openinframap/openinframap#182]
How reproduce:
- Open this URL https://openinframap.org/#12.08/49.42711/6.2245
- Select Cattenom power plant, click on more info -> error `Internal Server Error`

Open more info open this url https://openinframap.org/stats/object/plant/24041917
But open same power plant from stats open https://openinframap.org/stats/area/France/plants/24041917

IMO, problem is here https://github.com/openinframap/openinframap/blob/7dd061e5e8502ac6eb14c3173b8e7ec975b2bc46/web/src/infopopup.ts#L231
But that's requires to get country where is localized power plant

**Comment by russss** [comment]
Thanks - I have no idea how this broke, but it was an error with the backend.
