### ISSUE TITLE
man_made=water_well areas show up weirdly

### ISSUE THREAD

**Issue by JesseWeinstein** [openinframap/openinframap#186]
[man_made=water_well](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dwater_well) can apparently (rarely) be mapped as an area, not just as a point. And that isn't handled well by the map; it shows each individual node in the way as a separate item.

### Screenshot
![image](https://github.com/user-attachments/assets/f7d00603-c77f-4e8b-8850-e0d654100703)

### Link to where this issue occurs on OpenInfraMap
https://openinframap.org/#14.88/42.4984/-71.41625/L,W
### Link to the corresponding entity on OpenStreetMap
https://www.openstreetmap.org/way/29776473#map=16/42.49735/-71.42119&layers=D

**Comment by russss** [comment]
This is now fixed but caching means it may take a while to disappear.
