### ISSUE TITLE
Support switch=* tags on power=pole/tower

### ISSUE THREAD

**Issue by russss** [openinframap/openinframap#19]
https://wiki.openstreetmap.org/wiki/Tag:power=switch

**Comment by gustavecha** [comment]
We can also find transformers on tower/pole/portals
https://wiki.openstreetmap.org/wiki/Tag:power%3Dtransformer#Distribution_transformers

**Comment by pyrog** [comment]
Switch are not yet rendered. Could you reopen this issue please?

[node/6316737396
<img width="503" alt="Capture d’écran 2019-03-19 à 17 34 42" src="https://user-images.githubusercontent.com/2158081/54624357-8254d880-4a6d-11e9-86ab-c9fc3a4444b3.png">](https://openinframap.org/#17.76/46.52792/5.548473)

**Comment by russss** [comment]
These have now been added.
