### ISSUE TITLE
Are [name] tags used or [wikipedia] tags?

### ISSUE THREAD

**Issue by maro-21** [openinframap/openinframap#194]
I noticed that instead of [name], the names of Wikipedia articles are displayed.... Why is this and is it possible to change it?

**Comment by russss** [comment]
I'm not sure what you mean here - can you give me an example?

**Comment by maro-21** [comment]
For example:
https://openinframap.org/#12.39/51.13454/16.88756/L
It displays
Leśnica (Wrocław)
Złotniki (Wrocław)
Żerniki (Wrocław)

While there are no such names in any [name] tag:
https://osm.org/relation/2821413 / https://osm.org/node/443437990
https://osm.org/relation/16419064 / https://osm.org/node/443437993
https://osm.org/relation/2336904 / https://osm.org/node/1294563552

So do these names come from [wikipedia] tag??

**Comment by russss** [comment]
Ah, these come from the base map, which is external to OpenInfraMap. I believe the [OpenMapTiles](https://github.com/openmaptiles/openmaptiles) toolchain is responsible.

I am aiming to update/replace the basemap at some point soon, but I haven't yet decided what to use.
