### ISSUE TITLE
Render pipelines

### ISSUE THREAD

**Issue by pietervdvn** [openinframap/openinframap#22]
It would be cool to provide rendering of `man_made=pipeline` which transport all kinds of substances, such as oil, water, heat or beer.

### Link to where this issue occurs on OpenInfraMap
https://openinframap.org/#13/51.2118/3.2211/Power-Telecoms-Petroleum-Water

### Link to the corresponding entity on OpenStreetMap
Examples are:
https://www.openstreetmap.org/way/559807571
https://www.openstreetmap.org/way/465064529

**Comment by pyrog** [comment]
Saw [brine](https://en.wikipedia.org/wiki/Brine) pipeline on the field (saumoduc in french).

[Overpass query](http://overpass-turbo.eu/s/JJx)

Examples:

- [France](https://www.openstreetmap.org/way/202953873)
- [Germany](https://www.openstreetmap.org/way/488200392)

**Comment by russss** [comment]
I've just added water, wastewater, etc to the Water layer - I think that's most pipelines being shown now. Except the beer, maybe we need a beer layer.
