### ISSUE TITLE
Central office does not appear on the map

### ISSUE THREAD

**Issue by atabaraud** [openinframap/openinframap#23]
Hi,

I have seen a problem, when you tag a central office on OSM with a node, it does not appear on openinframap, you need to tag a building to see the central office on openinframap.

Sometimes it is not possible to tag a central office on a building because it is shared with other activities and telecom is not the major activity, in this case you need to tag the central office with a node

**Comment by gustavecha** [comment]
A recent new schema has been introduced in OSM regarding telecom local loops.
Central offices and telephone exchange are now mapped with teleocm=exchange tag.
They can be both mapped as nodes (street cabinets) or areas (buildings)
telecom=central_office and man_made=telephone_office are no longer used to map such features, and style should be updated to encourage the new tagging

**Comment by flacombe** [comment]
Example of render here with coloured dots
http://map.infos-reseaux.com/#15.29/45.568833/5.919302

Same logic than substations is applied with small dots = local facilities and big ones = telecom exchanges.
