### ISSUE TITLE
Add telecom=exchange tag

### ISSUE THREAD

**Issue by russss** [openinframap/openinframap#43]

**Comment by flacombe** [comment]
This would make #23 much easier to solve

**Comment by flacombe** [comment]
I add following to the list :
telecom=connection_point
telecom=distribution_point
telecom:medium=*

**Comment by MrPozor** [comment]
> I add following to the list :
> telecom=connection_point
> telecom=distribution_point
> telecom:medium=*

I concur. Would be great to see those included on the map.

**Comment by flacombe** [comment]
Here is a demonstration with exchanges and connection_points in Orleans, France.
http://map.infos-reseaux.com/#12.4/47.8994/1.94604

Source is available : https://github.com/flacombe/oim-web/blob/master/src/style/style_oim_telecoms.js

Orange is for copper and green for fibre medium (telecom:medium key).

![Capture d’écran du 2020-03-20 22-39-33](https://user-images.githubusercontent.com/5690599/77208395-fc45f480-6afb-11ea-869b-d61dc0846629.png)

**Comment by MrPozor** [comment]
Wow, that's great, thanks for the link. Much better map representation for my purpose (mapping of fibre cabinets).

**Comment by russss** [comment]
This is actually now being imported, I just need to render them. Hopefully that'll happen soon, it's a bit hectic here at the moment.

**Comment by flacombe** [comment]
That's good news @russss 

@MrPozor In which area are you mapping fibre cabinets?
Interested in feedbacks regarding proposed tagging

**Comment by MrPozor** [comment]
The ones in Villenave d'Ornon in France have been created by me:
http://map.infos-reseaux.com/#15.24/44.766423/-0.553253
