### ISSUE TITLE
Render pipeline=substation

### ISSUE THREAD

**Issue by pyrog** [openinframap/openinframap#45]
Hi Russ,

Could you render theses (gaz, oil...) substations?

There is 7578 objects according to [TagInfo](https://taginfo.openstreetmap.org/tags/pipeline=substation).
`pipeline=substation` is documented on the [wiki](pipeline=substation).

Examples:
* [Gas substation](https://www.openstreetmap.org/way/317264965)
* [Oil substation](https://www.openstreetmap.org/way/634878299#map=19/45.61222/5.93075)

See also #2

**Comment by russss** [comment]
Yes, I'll make sure these are added on reimport. I'd also recommend tagging them as `landuse=industrial` `industrial=[oil|gas]` though, which is already rendered.

**Comment by flacombe** [comment]
IMHO landuse=industrial + industrial=* shouldn't be used on openinframap as it doesn't represent a site but an area with high probability to find technical facilities.

pipeline=substation is the only feature corresponding to facilities dedicated to pipeline operations.

You won't find industrial=power to tag power substations

**Comment by russss** [comment]
I only render industrial=oil and industrial=gas, which are also used for things like oil refineries and storage facilities which shouldn't be (entirely) tagged as pipeline=substation.

**Comment by flacombe** [comment]
Understood
It may be a good deal prior to define more precise tagging for such facilities.

**Comment by pyrog** [comment]
Hi russss, 

In France, there is [434](http://overpass-turbo.eu/s/JJt) `pipeline=substation` and "only" [118](http://overpass-turbo.eu/s/JJv) `industrial=gas`.
[Here](https://openinframap.org/#15.77/46.341184/5.212275), the is a huge substation that is not yet rendered.

Could you reimport datas in order to display pipeline substations ?
It will really help us to edit the map :)

Thanks,
__
Yves

See also  #32

**Comment by russss** [comment]
It will be in the next import.

**Comment by claudiush** [comment]
Any chance for a re-import in 2022? I recently added a bunch of pipeline substation objects with
```
pipeline=substation
substation=distribution
substance=gas
```
Example object: https://www.openstreetmap.org/way/618236518

...and it's odd to see them not showing up on the gas and oil view of openinframap: https://openinframap.org/#15.1/35.95407/59.21758/L,O

**Comment by flacombe** [comment]
I second @claudiush tagging and wishes.

It may be an opportunity to get a better distinguish between substations and actual industrial facilities (refineries, plants...)

**Comment by russss** [comment]
I think this one got sorted a while ago.
