### ISSUE TITLE
Render names of pipelines

### ISSUE THREAD

**Issue by pyrog** [openinframap/openinframap#48]
Like power lines, could you display pipelines names ?

Currently, only the operator and the substance are rendered ([Example](https://openinframap.org/#14.43/48.72957/-1.28753)).

[![Pipeline name "Brécey Tirepied" not rendered](https://user-images.githubusercontent.com/2158081/59060704-f13e1280-88a1-11e9-8439-e9d3f6705f98.png)](https://openinframap.org/#12.18/48.72818/-1.2272)

**Comment by russss** [comment]
Fixed.
