### ISSUE TITLE
Render line_attachment property

### ISSUE THREAD

**Issue by flacombe** [openinframap/openinframap#53]
Hi

Recently, line_attachment property has been reviewed by OSM community.
It enables mappers to state how a line is bound to its supports.
See : https://wiki.openstreetmap.org/wiki/Key:line_attachment

It may be great to adapt towers and poles render according to this key on highest zooms, at least to show anchor and suspension values.
Let's say to use arrow heads on anchor supports and orthogonal straight line for suspension (i'll try to draw one of those days to make it clearer).

Let's discuss on the topic, all the best

**Comment by russss** [comment]
More discussion of this in #160, so I'll close this one.
