### ISSUE TITLE
Render power=generator devices

### ISSUE THREAD

**Issue by flacombe** [openinframap/openinframap#57]
Currently, only power plants are rendered and eventually wind turbines and solar panels.

Is it possible to add other kind of generators, simply displayed as big dots with colors according to generator:source please?

Look here : https://www.openstreetmap.org/node/6720055778
This would allow to see water turbines

All the best

**Comment by tilmanb** [comment]
+1. I miss a "power from waste" plant here: https://openinframap.org/#17.26/50.161302/8.636602

**Comment by russss** [comment]
I have all these imported already, however I would really like some nice icons to use for them. Coloured dots are already over-used and adding different items as dots will make the map quite confusing.

**Comment by flacombe** [comment]
This is quite unavoidable when you mix several domains like power and telco.

At least you won't be able to use proper icons at lower zoom levels as generators may be grouped on a small area.

**Comment by DerDakon** [comment]
Am I wrong or are solar generators not rendered if they are mapped as nodes?

**Comment by AlexJacu** [comment]
Also photovoltaic generator is only rendered if it is area, but not if it is a point

**Comment by AlexJacu** [comment]
Still only photovoltaic area is rendered, but nodes are not shown.
nearly ALL Small photovoltaic plants on homes are rendered as nodes.

**Comment by AlexJacu** [comment]
For small photovoltaik (on Roofs) you can use a yellow colored version of this and for plants (areas) another color like orange

![image](https://github.com/openinframap/openinframap/assets/22580543/a06e70fe-8acc-48e3-8e39-9e66b97d2cc2)

**Comment by flacombe** [comment]
Hello

I think it's way too prominent for domestic roof panels.
There could be dots, not much more because it's not the only feature to display on the map.

Finally it should be consistent with other generators.

**Comment by russss** [comment]
These are now being rendered.
