### ISSUE TITLE
Handle local references

### ISSUE THREAD

**Issue by flacombe** [openinframap/openinframap#65]
OSM widely uses ref=* to indicate the reference of a feature often assciated with a readable name=*

There are also some local reference to display that best describe features than ref=* which reflects the read value directly on ground when visible

Handling of such may be quite easy as only one ref is defined simultaneously
* ref:EU:ENTSOE_EIC https://wiki.openstreetmap.org/wiki/Key:ref:EU:ENTSOE_EIC
* ref:FR:RTE https://wiki.openstreetmap.org/wiki/Key:ref:FR:RTE
* ref:ERDF:gdo https://wiki.openstreetmap.org/wiki/Key:ref:ERDF:gdo
* ref:FR:ARCEP https://wiki.openstreetmap.org/wiki/Key:ref:FR:ARCEP
* ref:FR:ANFR https://wiki.openstreetmap.org/wiki/Key:ref:FR:ANFR
* ref:FR:PTT https://wiki.openstreetmap.org/wiki/Key:ref:FR:PTT

And so on...

**Comment by russss** [comment]
Yeah, it seems like there is a way of doing this so I'll add this on the next reimport.

(I also need to add [repd:id](https://wiki.openstreetmap.org/wiki/Key:repd:id) which unfortunately is not in ref: namespace although it should be.)

**Comment by flacombe** [comment]
Great to read you'll handle it, thanks

repd:id is too narrow to be outside ref=*
I've suggested a replacement on the Talk page : https://wiki.openstreetmap.org/wiki/Talk:Key:repd:id#Move_to_ref_namespace

**Comment by russss** [comment]
All refs are now shown on the stats page for a plant, which is now linked from the info popup.
