### ISSUE TITLE
Electric pole names should be shown, along with their refs

### ISSUE THREAD

**Issue by jidanni** [openinframap/openinframap#70]
Where I live, electric pole **names** are just as important as their **refs**
https://www.openstreetmap.org/node/4778301530
Alas, openinframap only shows the latter.

**Comment by flacombe** [comment]
Can you elaborate on what a name means for a power pole please?

What usecases are built on name and what other usecases rely on refs?

**Comment by jidanni** [comment]
Firstly, the "ref" is of course extremely important for rescues
https://udn.com/news/story/7320/4257321
https://wiki.osgeo.org/wiki/Taiwan_Power_Company_grid
https://www.jidanni.org/geo/taipower/

But let's not forget police driving along a road looking for
pole "Qingfu #61".

Well the know it must be between #60 and #62.

Yes the pole label plates also bear the refs, but they are grids like
G8354HA27
G8353HE22
G8353HE27
i.e., not something we can tell police clearly.

The plates have both the name and ref on them, so should the map.

**Comment by flacombe** [comment]
Thank you for making this clear to me

I still don't get why G8354HA27 has less meaning than "Qingfu #61"
What is Qingfu ? The line name ?

I'm not opposed to use name=* Just trying to figure out the exact meaning of both information

**Comment by jidanni** [comment]
Yes, the line name.
So each pole's [label](https://wiki.osgeo.org/wiki/File:Taipower.G8152fc56.jpg) has both a grid coordinate, and a linear address. The former pins down the X and Y, and is great for dramatic helicopter rescues. And the latter is great for police with their flashlights looking for pole # 61.

**Comment by jidanni** [comment]
(Not all [poles have bonus coordinates](https://en.wikipedia.org/wiki/Utility_pole#Coordinates_on_pole_tags).
Let's take the [nearby Taiwan telephone poles](http://web.archive.org/web/20161101200731/http://www.panoramio.com/photo/113146120).
They simply have line name + pole number.)

**Comment by jidanni** [comment]
In fact the Labels item,
![20211006T054105](https://user-images.githubusercontent.com/1230959/136106772-0247510d-334a-44f0-801c-461e807998ae.jpg)
could have subitems, with your default:

- [x] ref
- [ ] name

**Comment by russss** [comment]
These are now shown (they're used for the names of the pole-mounted transformers in the UK)
