### ISSUE TITLE
Voltage below 1 kV are displayed as 0 kV

### ISSUE THREAD

**Issue by pyrog** [openinframap/openinframap#82]
voyage=400
https://www.openstreetmap.org/way/410277097
https://openinframap.org/#17.9/48.461347/7.968078
<img width="631" alt="Capture d’écran 2020-07-12 à 23 15 24" src="https://user-images.githubusercontent.com/2158081/87256739-9e1b9380-c495-11ea-88f0-78e19df947de.png">

**Comment by russss** [comment]
This is fixed now, might take a little while for the cache to clear.

**Comment by flacombe** [comment]
Thank you

Sounds like it remains a little difference with infobox
![image](https://user-images.githubusercontent.com/5690599/133148267-d4db38dc-36f3-4c0c-9880-a65e358f85ce.png)

**Comment by russss** [comment]
That's fixed as well now.
