### ISSUE TITLE
[FR] Display ref_name if no ref is found

### ISSUE THREAD

**Issue by martinum4** [openinframap/openinframap#85]
A lot of power substations don't contain visible reference numbers but are instead marked with reference names.
These are usually tagged as ref_name=*
Example:

https://www.openstreetmap.org/way/385910158 -> https://openinframap.org/#17.9/51.305535/9.652998/P

**Comment by flacombe** [comment]
Hi @martinum4 

ref_name is not recommended tagging.
Such infrastructure usually have refs and usual names. Both of them may be displayed on power substations but they should be confused.
A usual name is intended for operators while refs are mainly intended to make mappings with databases.
We can't deduce from ref_name if it refers to a database or intended for display.

If the name is used as a reference, then simpler ref=* should be used. If not, name=* is suitable.

All the best

**Comment by russss** [comment]
I'm going to trust @flacombe on this one and close this as it's not something we should be rendering.
