### ISSUE TITLE
Extend water catogorie with things like dykes, locks, water treatment etc.

### ISSUE THREAD

**Issue by vincentvd1** [openinframap/openinframap#98]
I think the water section is a bit empty now while there is a lot of water infrastructure mapped. Think about:
- Dykes (and en general flood prevention features [like](https://www.openstreetmap.org/relation/9669291#map=13/51.6251/3.7315&layers=N) 
- Weirs ([like](https://www.openstreetmap.org/way/282795014))
- Locks ([like](https://www.openstreetmap.org/way/436343070))
- Water treatment facilities ([like](https://www.openstreetmap.org/way/383677128))

I think these are also part of the infrastructure and should be rendered. A lot of these objects are hidden on OSM. Let me hear what you think.

**Comment by russss** [comment]
I have now added water and sewage treatment plants.

I decided not to add locks, weirs, etc - it would be great to have a good technical map of those, but I think the scope would quickly increase and I don't think I have enough time to devote to that at the moment. (Maybe it will be something which [waterwaymap.org](https://waterwaymap.org) covers eventually.)

**Comment by foenyx** [comment]
"I decided not to add locks, weirs, etc" 

Could you consider to still add water towers ( man_made=water_tower ) ? 
- These are usually highly visible elements of water distribution networks
- They are related to man_made=reservoir_covered (which are shown on the map)  
- They are out of the scope of waterwaymap.org

**Comment by russss** [comment]
I have the data imported for water towers but presently I don't have an icon for them so they aren't yet displayed.
